name: true_match_coach
description: A Flutter-based AI-powered dating assistance app.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  http: ^0.13.0
  image_picker: ^0.8.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/questions.json