name: Build Flutter Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Projekt auschecken
      - uses: actions/checkout@v3

      # 2) Flutter installieren
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      # 3) Android-Grundgerüst anlegen (falls nicht vorhanden)
      - name: Ensure Android project exists
        run: flutter create --platforms=android .

      # 4) Abhängigkeiten holen
      - name: Install dependencies
        run: flutter pub get

      # 5) APK bauen
      - name: Build APK
        run: flutter build apk --release

      # 6) Fertige APK hochladen
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
